version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-test
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Test Company"
      LDAP_DOMAIN: "testcompany.com"
      LDAP_BASE_DN: "dc=testcompany,dc=com"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CONFIG_PASSWORD: "config123"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"  # Disable TLS for testing
      LDAP_TLS_CRT_FILENAME: ""
      LDAP_TLS_KEY_FILENAME: ""
      LDAP_TLS_DH_PARAM_FILENAME: ""
      LDAP_TLS_CA_CRT_FILENAME: ""
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: ldap.testcompany.com

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-test
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap
